{% set name = "mne-nirs" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3a757d9669015616aeebab32fe2d01aa4e59dfb74deecb5f65899aeae911fc72

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - mne-base >=1.0
    - ipyvtklink
    - seaborn
    - statsmodels
    - nilearn
    - h5io >=0.1.7

test:
  imports:
    - mne_nirs
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import mne_nirs; assert mne_nirs.__version__ == '{{ version }}', mne_nirs.__version__"

about:
  home: https://mne.tools/mne-nirs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Process Near-Infrared Spectroscopy Data in MNE.
  doc_url: https://mne.tools/mne-nirs
  dev_url: https://github.com/mne-tools/mne-nirs

extra:
  recipe-maintainers:
    - larsoner
    - rob-luke
    - hoechenberger
