{% set name = "mne-nirs" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cacda4022505781bca61b3a8dcefc82b20d54ccbbf08de44c083a79b64fbfeb1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - mne-base >=0.24
    - ipyvtklink
    - seaborn
    - statsmodels
    - nilearn
    - h5io >=0.1.7

test:
  imports:
    - mne_nirs
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://mne.tools/mne-nirs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Process Near-Infrared Spectroscopy Data in MNE.
  doc_url: https://mne.tools/mne-nirs
  dev_url: https://github.com/mne-tools/mne-nirs

extra:
  recipe-maintainers:
    - larsoner
    - rob-luke
    - hoechenberger
